// Generated by npm run db:readiness:generate. Do not edit.
// Runtime data only: no SQL files, catalog definitions or migration tooling.
export const DB_READINESS_MANIFEST = {
  "minimumVersion": 2,
  "maximumKnownVersion": 3,
  "runnerVersion": 1,
  "migrations": [
    {
      "version": 1,
      "filename": "0001_pre_41_baseline.sql",
      "sha256": "a01c8ab5d91939d731c71571ede83bfc4e6123ef1f61b8a0918f4f951f306c98"
    },
    {
      "version": 2,
      "filename": "0002_market_observation_history.sql",
      "sha256": "df35a458b5d6e3f26cbbdd84d8cfa65244e865dd6963b6f0e1f8f5f0e8dd7297"
    },
    {
      "version": 3,
      "filename": "0003_predictive_local_replay.sql",
      "sha256": "33c06dcc54dea80ab7e7cc9c6071f420dee184ca81608f618d7cff366b338bad"
    }
  ],
  "requiredTables": [
    "creator_video_submissions",
    "creators",
    "event_market_odds_cache",
    "live_prop_inputs_cache",
    "nflverse_roster_players",
    "odds_api_request_log",
    "odds_collection_checkpoints",
    "odds_free_pilot_selections",
    "odds_observation_book_markets",
    "odds_observation_markets",
    "odds_observations",
    "odds_priority_targets",
    "odds_quote_sets",
    "odds_quotes",
    "player_crosswalk",
    "player_game_stats",
    "sync_state"
  ]
} as const;
