-- Generated by npm run db:migrations:generate from ordered migration files.
-- Reference only; use the migration runner for schema delivery.

-- #26: historical player-stat source. Run this once against the
-- provisioned Neon/Vercel Postgres instance before the sync route can
-- write anything real.
--
-- Deliberately separate from Firestore's per-user app state (goal,
-- watchlist, matchupConfig) -- this is relational/time-series game-log
-- data (range queries by date, keyed by player + stat type), not
-- per-user state, so it lives in its own store.

-- One row per player, per game, per supported stat type -- long/tidy,
-- not nflverse's own wide (~150-column) shape. Ingestion melts their
-- wide per-week row down to just the stat types we actually support as
-- prop markets; there's no reason to store the other ~145 columns we'll
-- never query.
CREATE TABLE IF NOT EXISTS player_game_stats (
  id BIGSERIAL PRIMARY KEY,
  player_id TEXT NOT NULL,
  player_name TEXT NOT NULL,
  team TEXT NOT NULL,
  opponent TEXT NOT NULL,
  -- Derived at ingestion time, not sourced directly: nflverse's weekly
  -- stats file has no is_home/game_date columns at all, only game_id
  -- (format "{season}_{week}_{away}_{home}"). Both come from joining
  -- against nflverse's separate schedules release via that same
  -- game_id. Not consumed by computeEV today either way -- captured
  -- because it's a free column off data we're already joining in, not
  -- because anything needs it yet.
  is_home BOOLEAN NOT NULL,
  season INTEGER NOT NULL,
  week INTEGER NOT NULL,
  -- Also from the schedules join -- nflverse's weekly stats file has no
  -- calendar date of its own, only a season/week pair.
  game_date DATE NOT NULL,
  stat_type TEXT NOT NULL,
  stat_value NUMERIC NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  -- Makes ingestion idempotent: re-running a sync (or a Wednesday
  -- corrections pass revising an already-ingested week) upserts in
  -- place instead of creating duplicate rows.
  UNIQUE (player_id, season, week, stat_type)
);

-- The actual query computeEV's sample-window needs: "last N games for
-- this player + stat type, most recent first."
CREATE INDEX IF NOT EXISTS idx_player_game_stats_lookup
  ON player_game_stats (player_id, stat_type, game_date DESC);

-- The idempotency high-water-mark from the scheduling-landmine
-- discussion: before downloading nflverse's actual data file, the sync
-- route checks the GitHub Releases API's cheap metadata response and
-- compares the current season's asset `updated_at` against the value
-- stored here. Only downloads + upserts if it's newer; otherwise a safe
-- no-op, regardless of whether the cron fired before that week's file
-- was actually refreshed.
CREATE TABLE IF NOT EXISTS sync_state (
  source_name TEXT PRIMARY KEY,
  last_synced_asset_updated_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Durable identity cache: The Odds API's prop outcomes key off a plain
-- player-name string (its `description` field), while nflverse keys off
-- a GSIS player id. A cache miss is resolved conservatively against the
-- current event's two teams and market-compatible roster positions;
-- ambiguous or low-confidence names are never inserted.
CREATE TABLE IF NOT EXISTS player_crosswalk (
  odds_api_name TEXT PRIMARY KEY,
  nflverse_player_id TEXT NOT NULL,
  nflverse_player_name TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- #32: current-season identity source for conservative on-demand
-- crosswalk matching. This stays separate from player_game_stats:
-- stats contain abbreviated display names and omit players who have
-- not recorded a supported stat, while the roster supplies full names,
-- current team, position, and the same GSIS id used by the stats rows.
-- source_updated_at identifies one complete upstream roster snapshot;
-- reads use only the newest snapshot for a season, so a player removed
-- from a later source file cannot remain an active matching candidate.
CREATE TABLE IF NOT EXISTS nflverse_roster_players (
  season INTEGER NOT NULL,
  player_id TEXT NOT NULL,
  full_name TEXT NOT NULL,
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  football_name TEXT,
  team TEXT NOT NULL,
  position TEXT NOT NULL,
  status TEXT NOT NULL,
  source_updated_at TIMESTAMPTZ NOT NULL,
  synced_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (season, player_id)
);

CREATE INDEX IF NOT EXISTS idx_nflverse_roster_match_candidates
  ON nflverse_roster_players (season, source_updated_at DESC, team);

-- #34: creator-content confidence layer, transcript submission form.
-- Manual sourcing only (no scraper -- see the issue for why) -- these
-- tables just persist what's pasted through the internal submission
-- form, for #35's extraction pipeline to consume later. transcript_text
-- is stored as ONE raw blob per video; segmenting/parsing it into
-- structured picks is #35's job, not this one.
CREATE TABLE IF NOT EXISTS creators (
  id BIGSERIAL PRIMARY KEY,
  channel_name TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS creator_video_submissions (
  id BIGSERIAL PRIMARY KEY,
  creator_id BIGINT NOT NULL REFERENCES creators(id),
  -- Required (2026-09-29 revision) -- it's the only real dedup key
  -- (matches on video_title alone would be far too fragile) and #35/
  -- #36 need a real source link for evidence/traceability. video_title
  -- stays nullable -- real submissions have often had a blank one.
  video_url TEXT NOT NULL UNIQUE,
  video_title TEXT,
  transcript_text TEXT NOT NULL,
  submitted_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Follow-up correction to the original (nullable) column definition
-- above -- ALTER COLUMN ... SET NOT NULL is itself idempotent (a
-- harmless no-op if already NOT NULL), so this stays safe to re-run
-- alongside the CREATE TABLE IF NOT EXISTS statements on an existing
-- database that predates this revision.
ALTER TABLE creator_video_submissions ALTER COLUMN video_url SET NOT NULL;

CREATE INDEX IF NOT EXISTS idx_creator_video_submissions_creator
  ON creator_video_submissions (creator_id, submitted_at DESC);

-- #27: per-(event, market) odds cache. Discovering a game's available
-- player props costs real API credits (1 per market requested), so
-- caching at whole-event or per-player granularity would either
-- re-charge for markets already fetched moments ago, or fail to share
-- one market's data across every player who has a line in it. Keying
-- on (event_id, market_key) means the FIRST check of e.g. "Passing
-- Yards" for a game pays once, and every other request for that same
-- market on that same game -- regardless of which player it's for --
-- reuses it until fetched_at ages past the app's TTL (oddsCacheRepo.ts
-- owns that TTL, not this table).
CREATE TABLE IF NOT EXISTS event_market_odds_cache (
  event_id TEXT NOT NULL,
  market_key TEXT NOT NULL,
  -- Raw-ish bookmakers/markets/outcomes slice for just this one market,
  -- as returned by the Odds API -- not reshaped into an app-level prop
  -- type. Keeps this table a pure cache of what the API said, so a
  -- future change to how props are grouped/displayed doesn't require a
  -- cache-schema migration.
  payload JSONB NOT NULL,
  fetched_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (event_id, market_key)
);

-- #28: distributed live odds/weather cache. The serving key is one
-- player prop within a sport/event/market; bookmaker and direction are
-- intentionally absent because one upstream market response contains
-- every book and both Over/Under sides. All watchers of that prop share
-- one refreshed payload, even when they run on different serverless
-- instances or select different books/sides.
--
-- refresh_owner/refresh_lease_until form a short database-backed lease.
-- A crashed refresher cannot hold the key forever; another instance may
-- take over after the lease expires. payload/fetched_at are nullable only
-- while the first refresh for a new key is in flight.
CREATE TABLE IF NOT EXISTS live_prop_inputs_cache (
  sport_key TEXT NOT NULL,
  event_id TEXT NOT NULL,
  market_key TEXT NOT NULL,
  player_name TEXT NOT NULL,
  payload JSONB,
  fetched_at TIMESTAMPTZ,
  refresh_owner TEXT,
  refresh_lease_until TIMESTAMPTZ,
  PRIMARY KEY (sport_key, event_id, market_key, player_name),
  CHECK ((payload IS NULL) = (fetched_at IS NULL))
);

-- #41: immutable market-observation history. One observation represents one
-- completed upstream response and therefore one honest point in time. Quote
-- values live in content-addressed sets so a later response with unchanged
-- prices still gets its own timestamp without duplicating every quote row.
CREATE TABLE IF NOT EXISTS odds_observations (
  id TEXT PRIMARY KEY,
  sport_key TEXT NOT NULL,
  event_id TEXT NOT NULL,
  home_team TEXT NOT NULL,
  away_team TEXT NOT NULL,
  event_start_time TIMESTAMPTZ NOT NULL,
  source TEXT NOT NULL CHECK (
    source IN ('scheduled', 'discovery', 'live', 'provider-historical')
  ),
  captured_at TIMESTAMPTZ NOT NULL,
  requested_markets TEXT[] NOT NULL,
  collection_profile TEXT,
  checkpoint_key TEXT,
  quota_remaining INTEGER CHECK (quota_remaining IS NULL OR quota_remaining >= 0),
  quota_used INTEGER CHECK (quota_used IS NULL OR quota_used >= 0),
  quota_last INTEGER CHECK (quota_last IS NULL OR quota_last >= 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CHECK (cardinality(requested_markets) > 0)
);

CREATE INDEX IF NOT EXISTS idx_odds_observations_event_cutoff
  ON odds_observations (event_id, captured_at DESC);

CREATE TABLE IF NOT EXISTS odds_quote_sets (
  id BIGSERIAL PRIMARY KEY,
  event_id TEXT NOT NULL,
  market_key TEXT NOT NULL,
  content_hash TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (event_id, market_key, content_hash)
);

CREATE TABLE IF NOT EXISTS odds_observation_markets (
  observation_id TEXT NOT NULL REFERENCES odds_observations(id),
  market_key TEXT NOT NULL,
  status TEXT NOT NULL CHECK (
    status IN ('returned', 'empty', 'invalid', 'unavailable')
  ),
  quote_set_id BIGINT REFERENCES odds_quote_sets(id),
  PRIMARY KEY (observation_id, market_key),
  CHECK ((status = 'returned') = (quote_set_id IS NOT NULL))
);

CREATE INDEX IF NOT EXISTS idx_odds_observation_markets_market
  ON odds_observation_markets (market_key, observation_id);

-- Provider last_update belongs to each bookmaker's market in the event-odds
-- response. It is observation metadata, not quote-set content: a bookmaker
-- can report a newer update time while all normalized prices remain equal.
CREATE TABLE IF NOT EXISTS odds_observation_book_markets (
  observation_id TEXT NOT NULL,
  market_key TEXT NOT NULL,
  bookmaker_key TEXT NOT NULL,
  provider_updated_at TIMESTAMPTZ,
  PRIMARY KEY (observation_id, market_key, bookmaker_key),
  FOREIGN KEY (observation_id, market_key)
    REFERENCES odds_observation_markets(observation_id, market_key)
);

CREATE TABLE IF NOT EXISTS odds_quotes (
  quote_set_id BIGINT NOT NULL REFERENCES odds_quote_sets(id),
  bookmaker_key TEXT NOT NULL,
  raw_player_name TEXT NOT NULL,
  player_id TEXT,
  direction TEXT NOT NULL CHECK (direction IN ('over', 'under')),
  point NUMERIC NOT NULL,
  decimal_price NUMERIC NOT NULL CHECK (decimal_price > 1),
  PRIMARY KEY (
    quote_set_id,
    bookmaker_key,
    raw_player_name,
    direction,
    point
  )
);

CREATE INDEX IF NOT EXISTS idx_odds_quotes_lookup
  ON odds_quotes (quote_set_id, raw_player_name, point, bookmaker_key);

-- One durable free-tier event choice per NFL week. Automatic selection never
-- drifts after a schedule flex; an explicit operator override may replace it.
CREATE TABLE IF NOT EXISTS odds_free_pilot_selections (
  week_start_time TIMESTAMPTZ PRIMARY KEY,
  week_end_time TIMESTAMPTZ NOT NULL,
  sport_key TEXT NOT NULL,
  event_id TEXT NOT NULL,
  home_team TEXT NOT NULL,
  away_team TEXT NOT NULL,
  event_start_time TIMESTAMPTZ NOT NULL,
  selection_reason TEXT NOT NULL CHECK (
    selection_reason IN ('latest-sunday', 'explicit-override')
  ),
  selected_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CHECK (week_start_time < week_end_time),
  CHECK (event_start_time >= week_start_time AND event_start_time < week_end_time)
);

-- Generic event-market targets are independent of creator picks. Any later
-- trigger can activate one without changing the collector's cadence contract.
CREATE TABLE IF NOT EXISTS odds_priority_targets (
  id TEXT PRIMARY KEY,
  sport_key TEXT NOT NULL,
  event_id TEXT NOT NULL,
  home_team TEXT NOT NULL,
  away_team TEXT NOT NULL,
  event_start_time TIMESTAMPTZ NOT NULL,
  market_keys TEXT[] NOT NULL,
  activated_at TIMESTAMPTZ NOT NULL,
  reason TEXT NOT NULL,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CHECK (cardinality(market_keys) > 0),
  CHECK (activated_at < event_start_time)
);

CREATE INDEX IF NOT EXISTS idx_odds_priority_targets_active_event
  ON odds_priority_targets (active, event_start_time, event_id);

-- Durable work ledger: leases make cron invocations safe to overlap, while
-- due windows prevent a late worker from spending quota to recreate stale work.
CREATE TABLE IF NOT EXISTS odds_collection_checkpoints (
  id TEXT PRIMARY KEY,
  kind TEXT NOT NULL CHECK (kind IN ('baseline', 'priority')),
  collection_profile TEXT NOT NULL CHECK (
    collection_profile IN ('free-pilot', 'paid-baseline', 'priority')
  ),
  target_id TEXT REFERENCES odds_priority_targets(id),
  sport_key TEXT NOT NULL,
  event_id TEXT NOT NULL,
  home_team TEXT NOT NULL,
  away_team TEXT NOT NULL,
  event_start_time TIMESTAMPTZ NOT NULL,
  market_keys TEXT[] NOT NULL,
  checkpoint_key TEXT NOT NULL,
  due_at TIMESTAMPTZ NOT NULL,
  due_window_end TIMESTAMPTZ NOT NULL,
  priority_rank INTEGER NOT NULL CHECK (priority_rank > 0),
  status TEXT NOT NULL DEFAULT 'pending' CHECK (
    status IN ('pending', 'claimed', 'completed', 'failed', 'skipped')
  ),
  claim_owner TEXT,
  claim_expires_at TIMESTAMPTZ,
  attempts INTEGER NOT NULL DEFAULT 0 CHECK (attempts >= 0),
  max_attempts INTEGER NOT NULL DEFAULT 3 CHECK (max_attempts > 0),
  next_attempt_at TIMESTAMPTZ,
  observation_id TEXT REFERENCES odds_observations(id),
  credit_cost INTEGER CHECK (credit_cost IS NULL OR credit_cost >= 0),
  schedule_reason TEXT NOT NULL,
  outcome_reason TEXT,
  last_error TEXT,
  completed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (collection_profile, event_id, checkpoint_key),
  CHECK (cardinality(market_keys) > 0),
  CHECK (due_at < due_window_end),
  CHECK (due_window_end <= event_start_time),
  CHECK ((kind = 'priority') = (target_id IS NOT NULL)),
  CHECK (
    (status = 'claimed' AND claim_owner IS NOT NULL AND claim_expires_at IS NOT NULL)
    OR
    (status <> 'claimed' AND claim_owner IS NULL AND claim_expires_at IS NULL)
  )
);

CREATE INDEX IF NOT EXISTS idx_odds_collection_checkpoints_due
  ON odds_collection_checkpoints (
    status,
    priority_rank,
    due_at,
    next_attempt_at,
    claim_expires_at
  );

CREATE INDEX IF NOT EXISTS idx_odds_collection_checkpoints_event
  ON odds_collection_checkpoints (event_id, due_at);

CREATE TABLE IF NOT EXISTS odds_api_request_log (
  id TEXT PRIMARY KEY,
  request_kind TEXT NOT NULL CHECK (request_kind IN ('events', 'event-odds')),
  source TEXT NOT NULL CHECK (source IN ('slate', 'discovery', 'live', 'scheduled', 'direct')),
  sport_key TEXT NOT NULL,
  event_id TEXT,
  requested_markets TEXT[] NOT NULL DEFAULT '{}',
  requested_at TIMESTAMPTZ NOT NULL,
  response_received_at TIMESTAMPTZ,
  outcome TEXT NOT NULL CHECK (
    outcome IN ('success', 'http-error', 'network-error', 'aborted')
  ),
  http_status INTEGER CHECK (http_status IS NULL OR http_status BETWEEN 100 AND 599),
  quota_remaining INTEGER CHECK (quota_remaining IS NULL OR quota_remaining >= 0),
  quota_used INTEGER CHECK (quota_used IS NULL OR quota_used >= 0),
  quota_last INTEGER CHECK (quota_last IS NULL OR quota_last >= 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CHECK ((request_kind = 'event-odds') = (event_id IS NOT NULL)),
  CHECK ((request_kind = 'event-odds') = (cardinality(requested_markets) > 0)),
  CHECK ((outcome IN ('success', 'http-error')) = (response_received_at IS NOT NULL)),
  CHECK (response_received_at IS NULL OR response_received_at >= requested_at),
  CHECK ((outcome = 'network-error' OR outcome = 'aborted') = (http_status IS NULL))
);

CREATE INDEX IF NOT EXISTS idx_odds_api_request_log_requested
  ON odds_api_request_log (requested_at DESC);

CREATE INDEX IF NOT EXISTS idx_odds_api_request_log_source
  ON odds_api_request_log (source, requested_at DESC);

-- Local synthetic persistence proof. No application route requires this prefix.
-- Source truth is append-only; a capture's routing timestamps never change.
CREATE FUNCTION public.predictive_text(value jsonb) RETURNS boolean
LANGUAGE sql IMMUTABLE STRICT AS $$
  SELECT jsonb_typeof(value) = 'string' AND length(value #>> '{}') BETWEEN 1 AND 256
    AND (value #>> '{}') !~ '[[:cntrl:]]' AND length(btrim(value #>> '{}')) > 0
$$;

CREATE FUNCTION public.predictive_instant(value text) RETURNS boolean
LANGUAGE plpgsql IMMUTABLE STRICT AS $$
BEGIN
  RETURN value ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}\.[0-9]{3}Z$'
    AND to_char(value::timestamptz AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"') = value;
EXCEPTION WHEN OTHERS THEN RETURN false;
END
$$;

CREATE FUNCTION public.predictive_integer(value jsonb, minimum numeric, maximum numeric) RETURNS boolean
LANGUAGE plpgsql IMMUTABLE STRICT AS $$
BEGIN
  RETURN jsonb_typeof(value) = 'number' AND (value #>> '{}')::numeric BETWEEN minimum AND maximum
    AND mod((value #>> '{}')::numeric, 1) = 0;
EXCEPTION WHEN OTHERS THEN RETURN false;
END
$$;

CREATE FUNCTION public.predictive_payload_valid(kind text, data jsonb) RETURNS boolean
LANGUAGE plpgsql IMMUTABLE STRICT AS $$
DECLARE fields text[]; name text; item jsonb;
BEGIN
  fields := CASE kind
    WHEN 'schedule' THEN ARRAY['gameId','rawGameId','season','seasonType','week','kickoff','homeTeamId','awayTeamId','rawHomeTeam','rawAwayTeam','mappingVersion']
    WHEN 'membership' THEN ARRAY['gameId','playerId','rawPlayerId','teamId','rawTeam','position','effectiveFrom','effectiveTo','mappingVersion']
    WHEN 'player-passing' THEN ARRAY['gameId','rawGameId','teamId','rawTeam','season','seasonType','attempts','passingYards','missingReason','playerId','rawPlayerId']
    WHEN 'team-passing' THEN ARRAY['gameId','rawGameId','teamId','rawTeam','season','seasonType','attempts','passingYards','missingReason']
    WHEN 'completion' THEN ARRAY['gameId','state','bound','boundKind','evidenceVersion']
    WHEN 'participation' THEN ARRAY['gameId','playerId','state','evidenceVersion']
    WHEN 'availability' THEN ARRAY['gameId','playerId','injury','depth','evidenceVersion']
    WHEN 'schedule-coverage' THEN ARRAY['teamId','fromSeason','throughSeason','gameIds','state','evidenceVersion']
    ELSE NULL END;
  IF fields IS NULL OR jsonb_typeof(data) <> 'object' OR
    (SELECT array_agg(key ORDER BY key) FROM jsonb_object_keys(data) key) IS DISTINCT FROM
    (SELECT array_agg(key ORDER BY key) FROM unnest(fields) key) THEN RETURN false; END IF;
  FOREACH name IN ARRAY ARRAY['rawGameId','rawTeam','rawHomeTeam','rawAwayTeam','mappingVersion','evidenceVersion','position'] LOOP
    IF data ? name AND NOT public.predictive_text(data->name) THEN RETURN false; END IF;
  END LOOP;
  IF data ? 'gameId' AND (jsonb_typeof(data->'gameId') <> 'string' OR data->>'gameId' !~ '^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$') THEN RETURN false; END IF;
  IF data ? 'playerId' AND (jsonb_typeof(data->'playerId') <> 'string' OR data->>'playerId' !~ '^00-[0-9]{7}$') THEN RETURN false; END IF;
  IF data ? 'rawPlayerId' AND data->'rawPlayerId' IS DISTINCT FROM data->'playerId' THEN RETURN false; END IF;
  FOREACH name IN ARRAY ARRAY['teamId','homeTeamId','awayTeamId'] LOOP
    IF data ? name AND (jsonb_typeof(data->name) <> 'string' OR data->>name !~ '^nfl:team:[A-Z]{2,3}$') THEN RETURN false; END IF;
  END LOOP;
  IF data ? 'season' AND (NOT public.predictive_integer(data->'season',1920,9999) OR (data->>'seasonType' IN ('REG','POST')) IS NOT TRUE) THEN RETURN false; END IF;
  CASE kind
    WHEN 'schedule' THEN
      RETURN public.predictive_integer(data->'week',1,22) AND public.predictive_instant(data->>'kickoff')
        AND data->>'homeTeamId' <> data->>'awayTeamId';
    WHEN 'membership' THEN
      RETURN public.predictive_instant(data->>'effectiveFrom') AND public.predictive_instant(data->>'effectiveTo')
        AND data->>'effectiveFrom' < data->>'effectiveTo';
    WHEN 'player-passing', 'team-passing' THEN
      IF data->'attempts' <> 'null'::jsonb AND NOT public.predictive_integer(data->'attempts',0,1000) THEN RETURN false; END IF;
      IF data->'passingYards' <> 'null'::jsonb AND NOT public.predictive_integer(data->'passingYards',-10000,10000) THEN RETURN false; END IF;
      RETURN CASE WHEN data->'attempts' = 'null'::jsonb OR data->'passingYards' = 'null'::jsonb
        THEN data->>'missingReason' IN ('source-blank','source-missing') ELSE data->'missingReason' = 'null'::jsonb END;
    WHEN 'completion' THEN
      RETURN CASE data->>'state' WHEN 'confirmed' THEN public.predictive_instant(data->>'bound') AND data->>'boundKind' IN ('actual-end','completion-observed-at')
        WHEN 'unresolved' THEN data->'bound' = 'null'::jsonb AND data->'boundKind' = 'null'::jsonb ELSE false END;
    WHEN 'participation' THEN RETURN data->>'state' IN ('confirmed','absent','unresolved');
    WHEN 'availability' THEN RETURN data->>'injury' IN ('unknown','eligible','excluded') AND data->>'depth' IN ('unknown','observed');
    WHEN 'schedule-coverage' THEN
      IF NOT public.predictive_integer(data->'fromSeason',1920,9999) OR NOT public.predictive_integer(data->'throughSeason',1920,9999)
        OR (data->>'throughSeason')::integer - (data->>'fromSeason')::integer <> 2
        OR (data->>'state' IN ('complete','incomplete')) IS NOT TRUE OR jsonb_typeof(data->'gameIds') <> 'array'
        OR jsonb_array_length(data->'gameIds') > 256 THEN RETURN false; END IF;
      FOR item IN SELECT value FROM jsonb_array_elements(data->'gameIds') LOOP
        IF jsonb_typeof(item) <> 'string' OR item #>> '{}' !~ '^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$' THEN RETURN false; END IF;
      END LOOP;
      RETURN (SELECT count(*) = count(DISTINCT value) FROM jsonb_array_elements(data->'gameIds'));
    ELSE RETURN false;
  END CASE;
EXCEPTION WHEN OTHERS THEN RETURN false;
END
$$;

CREATE TABLE public.predictive_ingestion_runs (
  id text PRIMARY KEY CHECK (length(id) BETWEEN 1 AND 256),
  request_sha256 text NOT NULL CHECK (request_sha256 ~ '^[a-f0-9]{64}$'),
  code_version text NOT NULL CHECK (code_version = 'predictive-local-store-v1'),
  adapter_version text NOT NULL CHECK (adapter_version = 'synthetic-json-v1'),
  started_at timestamptz NOT NULL CHECK (isfinite(started_at)),
  finished_at timestamptz NOT NULL CHECK (isfinite(finished_at) AND finished_at >= started_at),
  status text NOT NULL CHECK (status IN ('published','incomplete','refused')),
  failure_code text CHECK (failure_code IN ('publication-refused','artifact-store-unavailable','partial-acquisition')),
  artifact_count integer NOT NULL CHECK (artifact_count BETWEEN 0 AND 256),
  capture_count integer NOT NULL CHECK (capture_count BETWEEN 0 AND 512),
  row_count integer NOT NULL CHECK (row_count BETWEEN 0 AND 8192),
  bounds jsonb NOT NULL CHECK (bounds = '{"artifacts":256,"captures":512,"bytes":8000000,"rows":8192}'::jsonb),
  CHECK ((status = 'published') = (failure_code IS NULL))
);

CREATE TABLE public.predictive_artifacts (
  id text PRIMARY KEY CHECK (length(id) BETWEEN 1 AND 256),
  sha256 text NOT NULL CHECK (sha256 ~ '^[a-f0-9]{64}$'),
  byte_size integer NOT NULL CHECK (byte_size BETWEEN 0 AND 1000000),
  storage_ref text NOT NULL CHECK (storage_ref = sha256 || '.json'),
  source text NOT NULL CHECK (source = 'synthetic'),
  origin text NOT NULL CHECK (length(origin) BETWEEN 1 AND 256 AND origin !~ '[[:cntrl:]]'),
  feed text NOT NULL CHECK (feed IN ('schedule','membership','player-passing','team-passing','completion','participation','availability','schedule-coverage')),
  schema_version text NOT NULL CHECK (schema_version = 'predictive-proof-v1'),
  parser_version text NOT NULL CHECK (parser_version = 'synthetic-json-v1'),
  rights_review_version text NOT NULL CHECK (rights_review_version = 'synthetic-only-v1')
);
CREATE INDEX predictive_artifacts_content_idx ON public.predictive_artifacts (sha256);

CREATE TABLE public.predictive_captures (
  id text PRIMARY KEY CHECK (length(id) BETWEEN 1 AND 256),
  run_id text NOT NULL REFERENCES public.predictive_ingestion_runs(id),
  artifact_id text NOT NULL REFERENCES public.predictive_artifacts(id),
  captured_at timestamptz NOT NULL CHECK (isfinite(captured_at) AND captured_at = date_trunc('milliseconds', captured_at)),
  available_at timestamptz NOT NULL CHECK (isfinite(available_at) AND available_at = date_trunc('milliseconds', available_at) AND available_at >= captured_at),
  ingested_at timestamptz NOT NULL CHECK (isfinite(ingested_at) AND ingested_at = date_trunc('milliseconds', ingested_at) AND ingested_at >= available_at),
  published_at timestamptz CHECK (isfinite(published_at) AND published_at = date_trunc('milliseconds', published_at) AND published_at <= captured_at),
  publication_evidence text CHECK (length(publication_evidence) BETWEEN 1 AND 256 AND publication_evidence !~ '[[:cntrl:]]'),
  state text NOT NULL CHECK (state IN ('published','incomplete')),
  CHECK ((published_at IS NULL) = (publication_evidence IS NULL))
);
CREATE INDEX predictive_captures_cutoff_idx ON public.predictive_captures (artifact_id, available_at, ingested_at, id) WHERE state = 'published';

CREATE TABLE public.predictive_teams (
  id text PRIMARY KEY CHECK (id ~ '^nfl:team:(ARI|ATL|BAL|BUF|CAR|CHI|CIN|CLE|DAL|DEN|DET|GB|HOU|IND|JAX|KC|LAC|LAR|LV|MIA|MIN|NE|NO|NYG|NYJ|PHI|PIT|SEA|SF|TB|TEN|WAS)$')
);
CREATE TABLE public.predictive_games (
  id uuid PRIMARY KEY CHECK (id::text ~ '^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$')
);

-- JSON is an exact per-kind schema, not an open payload. Generated routing
-- columns and foreign keys bind its indexed identity to the validated payload.
CREATE TABLE public.predictive_observations (
  id text PRIMARY KEY CHECK (length(id) BETWEEN 1 AND 256),
  kind text NOT NULL,
  data jsonb NOT NULL CHECK (public.predictive_payload_valid(kind, data) IS TRUE),
  natural_key text GENERATED ALWAYS AS (kind || ':' || CASE WHEN kind = 'schedule-coverage'
    THEN (data->>'teamId') || ':' || (data->>'fromSeason') || ':' || (data->>'throughSeason')
    ELSE (data->>'gameId') || CASE WHEN data ? 'playerId' THEN ':' || (data->>'playerId')
      WHEN data ? 'teamId' THEN ':' || (data->>'teamId') ELSE '' END END) STORED,
  game_id uuid GENERATED ALWAYS AS ((data->>'gameId')::uuid) STORED REFERENCES public.predictive_games(id),
  player_id text GENERATED ALWAYS AS (data->>'playerId') STORED,
  team_id text GENERATED ALWAYS AS (data->>'teamId') STORED REFERENCES public.predictive_teams(id),
  home_team_id text GENERATED ALWAYS AS (data->>'homeTeamId') STORED REFERENCES public.predictive_teams(id),
  away_team_id text GENERATED ALWAYS AS (data->>'awayTeamId') STORED REFERENCES public.predictive_teams(id),
  season integer GENERATED ALWAYS AS ((data->>'season')::integer) STORED,
  effective_from text GENERATED ALWAYS AS (data->>'effectiveFrom') STORED,
  effective_to text GENERATED ALWAYS AS (data->>'effectiveTo') STORED,
  raw_game_id text GENERATED ALWAYS AS (data->>'rawGameId') STORED,
  predecessor_id text,
  correction_reason text CHECK (length(correction_reason) BETWEEN 1 AND 256 AND correction_reason !~ '[[:cntrl:]]'),
  UNIQUE (id, kind, natural_key),
  FOREIGN KEY (predecessor_id, kind, natural_key) REFERENCES public.predictive_observations(id, kind, natural_key) DEFERRABLE INITIALLY DEFERRED,
  CHECK ((predecessor_id IS NULL) = (correction_reason IS NULL)),
  CHECK (predecessor_id IS DISTINCT FROM id)
);
CREATE INDEX predictive_observations_entity_idx ON public.predictive_observations (game_id, kind, player_id, team_id);
CREATE INDEX predictive_observations_key_idx ON public.predictive_observations (natural_key);
CREATE INDEX predictive_observations_membership_idx ON public.predictive_observations (player_id, team_id, effective_from, effective_to) WHERE kind = 'membership';
CREATE INDEX predictive_observations_team_idx ON public.predictive_observations (team_id, kind);
CREATE INDEX predictive_observations_home_schedule_idx ON public.predictive_observations (home_team_id, season) WHERE kind = 'schedule';
CREATE INDEX predictive_observations_away_schedule_idx ON public.predictive_observations (away_team_id, season) WHERE kind = 'schedule';
CREATE INDEX predictive_observations_alias_idx ON public.predictive_observations (raw_game_id) WHERE kind = 'schedule';

CREATE TABLE public.predictive_artifact_observations (
  artifact_id text NOT NULL REFERENCES public.predictive_artifacts(id),
  observation_id text NOT NULL REFERENCES public.predictive_observations(id),
  PRIMARY KEY (artifact_id, observation_id)
);
CREATE INDEX predictive_artifact_observations_reverse_idx ON public.predictive_artifact_observations (observation_id, artifact_id);

CREATE FUNCTION public.predictive_append_only() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN RAISE EXCEPTION 'predictive-append-only' USING ERRCODE = '23514'; END
$$;
CREATE TRIGGER predictive_runs_immutable BEFORE UPDATE OR DELETE ON public.predictive_ingestion_runs FOR EACH ROW EXECUTE FUNCTION public.predictive_append_only();
CREATE TRIGGER predictive_artifacts_immutable BEFORE UPDATE OR DELETE ON public.predictive_artifacts FOR EACH ROW EXECUTE FUNCTION public.predictive_append_only();
CREATE TRIGGER predictive_captures_immutable BEFORE UPDATE OR DELETE ON public.predictive_captures FOR EACH ROW EXECUTE FUNCTION public.predictive_append_only();
CREATE TRIGGER predictive_teams_immutable BEFORE UPDATE OR DELETE ON public.predictive_teams FOR EACH ROW EXECUTE FUNCTION public.predictive_append_only();
CREATE TRIGGER predictive_games_immutable BEFORE UPDATE OR DELETE ON public.predictive_games FOR EACH ROW EXECUTE FUNCTION public.predictive_append_only();
CREATE TRIGGER predictive_observations_immutable BEFORE UPDATE OR DELETE ON public.predictive_observations FOR EACH ROW EXECUTE FUNCTION public.predictive_append_only();
CREATE TRIGGER predictive_links_immutable BEFORE UPDATE OR DELETE ON public.predictive_artifact_observations FOR EACH ROW EXECUTE FUNCTION public.predictive_append_only();
CREATE TRIGGER predictive_runs_no_truncate BEFORE TRUNCATE ON public.predictive_ingestion_runs FOR EACH STATEMENT EXECUTE FUNCTION public.predictive_append_only();
CREATE TRIGGER predictive_artifacts_no_truncate BEFORE TRUNCATE ON public.predictive_artifacts FOR EACH STATEMENT EXECUTE FUNCTION public.predictive_append_only();
CREATE TRIGGER predictive_captures_no_truncate BEFORE TRUNCATE ON public.predictive_captures FOR EACH STATEMENT EXECUTE FUNCTION public.predictive_append_only();
CREATE TRIGGER predictive_teams_no_truncate BEFORE TRUNCATE ON public.predictive_teams FOR EACH STATEMENT EXECUTE FUNCTION public.predictive_append_only();
CREATE TRIGGER predictive_games_no_truncate BEFORE TRUNCATE ON public.predictive_games FOR EACH STATEMENT EXECUTE FUNCTION public.predictive_append_only();
CREATE TRIGGER predictive_observations_no_truncate BEFORE TRUNCATE ON public.predictive_observations FOR EACH STATEMENT EXECUTE FUNCTION public.predictive_append_only();
CREATE TRIGGER predictive_links_no_truncate BEFORE TRUNCATE ON public.predictive_artifact_observations FOR EACH STATEMENT EXECUTE FUNCTION public.predictive_append_only();

CREATE FUNCTION public.predictive_publication_check() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE affected text[];
BEGIN
  IF TG_TABLE_NAME = 'predictive_captures' THEN
    IF NEW.state = 'published' AND (SELECT status FROM public.predictive_ingestion_runs WHERE id = NEW.run_id) <> 'published' THEN
      RAISE EXCEPTION 'predictive-publication-invalid' USING ERRCODE = '23514';
    END IF;
    SELECT array_agg(observation_id) INTO affected FROM public.predictive_artifact_observations WHERE artifact_id = NEW.artifact_id;
  ELSIF TG_TABLE_NAME = 'predictive_observations' THEN affected := ARRAY[NEW.id];
  ELSE affected := ARRAY[NEW.observation_id]; END IF;
  IF
    EXISTS (SELECT 1 FROM public.predictive_artifact_observations l JOIN public.predictive_observations o ON o.id = l.observation_id
      JOIN public.predictive_artifacts a ON a.id = l.artifact_id WHERE o.id = ANY(affected) AND o.kind <> a.feed) OR
    EXISTS (SELECT 1 FROM public.predictive_observations o WHERE o.id = ANY(affected) AND NOT EXISTS
      (SELECT 1 FROM public.predictive_artifact_observations l JOIN public.predictive_captures c ON c.artifact_id = l.artifact_id
        WHERE l.observation_id = o.id AND c.state = 'published')) THEN
    RAISE EXCEPTION 'predictive-publication-invalid' USING ERRCODE = '23514';
  END IF;
  -- Every correction's first usable capture must follow an independently
  -- usable predecessor. That also makes correction cycles impossible.
  IF EXISTS (SELECT 1 FROM public.predictive_observations o
    JOIN public.predictive_artifact_observations l ON l.observation_id = o.id
    JOIN public.predictive_captures c ON c.artifact_id = l.artifact_id AND c.state = 'published'
    WHERE o.id = ANY(affected) AND o.predecessor_id IS NOT NULL AND NOT EXISTS (
      SELECT 1 FROM public.predictive_artifact_observations pl JOIN public.predictive_captures pc ON pc.artifact_id = pl.artifact_id
      WHERE pl.observation_id = o.predecessor_id AND pc.state = 'published'
        AND pc.available_at <= c.available_at AND pc.ingested_at <= c.ingested_at)) THEN
    RAISE EXCEPTION 'predictive-correction-time-invalid' USING ERRCODE = '23514';
  END IF;
  IF EXISTS (WITH RECURSIVE chain AS (
    SELECT id, predecessor_id, ARRAY[id] AS path, false AS cycle FROM public.predictive_observations WHERE id = ANY(affected) AND predecessor_id IS NOT NULL
    UNION ALL SELECT c.id, o.predecessor_id, c.path || o.id, o.id = ANY(c.path)
      FROM chain c JOIN public.predictive_observations o ON o.id = c.predecessor_id WHERE NOT c.cycle)
    SELECT 1 FROM chain WHERE cycle) THEN
    RAISE EXCEPTION 'predictive-correction-cycle' USING ERRCODE = '23514';
  END IF;
  RETURN NULL;
END
$$;
CREATE CONSTRAINT TRIGGER predictive_check_captures AFTER INSERT ON public.predictive_captures DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION public.predictive_publication_check();
CREATE CONSTRAINT TRIGGER predictive_check_observations AFTER INSERT ON public.predictive_observations DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION public.predictive_publication_check();
CREATE CONSTRAINT TRIGGER predictive_check_links AFTER INSERT ON public.predictive_artifact_observations DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION public.predictive_publication_check();

-- Align the predictive team constraint with NFL_TEAM_ABBREVIATIONS.
-- V3 incorrectly accepted LAR, while the application's canonical Rams ID is LA.
-- Keep v3 bytes/checksums intact. Validate existing rows rather than rewriting
-- immutable identities or observations; an unmapped legacy LAR row refuses the
-- migration and the runner rolls back its DDL and ledger insertion.
ALTER TABLE public.predictive_teams
  DROP CONSTRAINT predictive_teams_id_check,
  ADD CONSTRAINT predictive_teams_id_check
    CHECK (id ~ '^nfl:team:(ARI|ATL|BAL|BUF|CAR|CHI|CIN|CLE|DAL|DEN|DET|GB|HOU|IND|JAX|KC|LA|LAC|LV|MIA|MIN|NE|NO|NYG|NYJ|PHI|PIT|SEA|SF|TB|TEN|WAS)$');
