import { createHash } from "node:crypto";
import { readFile, readdir } from "node:fs/promises";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { canonicalJson } from "../db-catalog.mjs";
import { refuse } from "./errors.mjs";

export const RUNNER_VERSION = 1;
export const migrationDirectory = fileURLToPath(new URL("../../db/migrations/", import.meta.url));
export const manifestPath = fileURLToPath(new URL("../../db/migration-manifest.json", import.meta.url));
export const schemaPath = fileURLToPath(new URL("../../db/schema.sql", import.meta.url));
const referenceHeader = "-- Generated by npm run db:migrations:generate from ordered migration files.\n" +
  "-- Reference only; use the migration runner for schema delivery.\n\n";

// Inspect statement starts without splitting SQL for execution. Ignore comments
// and quoted bodies so a function's dollar-quoted BEGIN is not mistaken for COMMIT.
export function assertTransactionalSql(sql) {
  const identifierCharacter = (character) => character !== undefined && /[A-Za-z0-9_$\u0080-\uFFFF]/.test(character);
  let stripped = "";
  for (let index = 0; index < sql.length;) {
    if (sql.startsWith("--", index)) {
      const end = sql.indexOf("\n", index);
      index = end === -1 ? sql.length : end + 1;
    } else if (sql.startsWith("/*", index)) {
      let depth = 1;
      index += 2;
      while (index < sql.length && depth) {
        if (sql.startsWith("/*", index)) { depth++; index += 2; }
        else if (sql.startsWith("*/", index)) { depth--; index += 2; }
        else index++;
      }
      if (depth) refuse("unterminated-migration-comment");
    } else if (["'", '"'].includes(sql[index])) {
      const quote = sql[index];
      const escaped = quote === "'" && /[eE]/.test(sql[index - 1] ?? "") && !identifierCharacter(sql[index - 2]);
      index++;
      let closed = false;
      while (index < sql.length) {
        if (escaped && sql[index] === "\\") { index += 2; continue; }
        if (sql[index] === quote) {
          if (sql[index + 1] === quote) { index += 2; continue; }
          index++; closed = true; break;
        }
        index++;
      }
      if (!closed) refuse("unterminated-migration-quote");
    } else {
      const delimiter = !identifierCharacter(sql[index - 1]) && /^\$(?:[A-Za-z_][A-Za-z_0-9]*)?\$/.exec(sql.slice(index))?.[0];
      if (delimiter) {
        const end = sql.indexOf(delimiter, index + delimiter.length);
        if (end === -1) refuse("unterminated-migration-quote");
        index = end + delimiter.length;
      } else { stripped += sql[index++]; continue; }
    }
    stripped += " ";
  }
  if (/(?:^|;)\s*(?:BEGIN|START\s+TRANSACTION|COMMIT|END|ROLLBACK|ABORT|SAVEPOINT|RELEASE|PREPARE\s+TRANSACTION)\b/i.test(stripped)) {
    refuse("migration-transaction-control-refused");
  }
  if (/(?:^|;)\s*(?:SET|RESET|DISCARD)\b/i.test(stripped)) refuse("migration-session-control-refused");
}

export async function readMigrationFiles(directory = migrationDirectory) {
  const entries = (await readdir(directory, { withFileTypes: true })).sort((a, b) => a.name.localeCompare(b.name, "en"));
  if (!entries.length) refuse("migration-files-required");
  const files = [];
  for (const [index, entry] of entries.entries()) {
    if (!entry.isFile() || !/^[0-9]{4}_[a-z][a-z0-9_]*\.sql$/.test(entry.name) ||
        Number(entry.name.slice(0, 4)) !== index + 1) refuse("invalid-migration-file-order");
    const bytes = await readFile(join(directory, entry.name));
    const sql = bytes.toString("utf8");
    if (!bytes.equals(Buffer.from(sql)) || sql.includes("\r") || sql.startsWith("\uFEFF") || !sql.trim() || !sql.endsWith("\n")) {
      refuse("migration-utf8-lf-required");
    }
    assertTransactionalSql(sql);
    files.push(Object.freeze({
      version: index + 1, filename: entry.name, sql,
      sha256: createHash("sha256").update(bytes).digest("hex"),
    }));
  }
  return Object.freeze(files);
}

export function buildManifest(files) {
  return { formatVersion: 1, runnerVersion: RUNNER_VERSION,
    migrations: files.map(({ version, filename, sha256 }) => ({ version, filename, sha256 })) };
}

export function validateManifest(manifest, files) {
  if (canonicalJson(manifest) !== canonicalJson(buildManifest(files))) refuse("migration-manifest-mismatch");
}

export function buildSchemaReference(files) {
  return referenceHeader + files.map((file) => file.sql).join("\n");
}

export async function loadMigrationSet(directory = migrationDirectory, path = manifestPath) {
  const files = await readMigrationFiles(directory);
  let manifest;
  try { manifest = JSON.parse(await readFile(path, "utf8")); }
  catch { refuse("invalid-migration-manifest"); }
  validateManifest(manifest, files);
  return files;
}

export async function checkMigrationArtifacts() {
  const files = await loadMigrationSet();
  if (await readFile(schemaPath, "utf8") !== buildSchemaReference(files)) refuse("migration-reference-drift");
  return files;
}
